---
- name: Check role inputs are valid
  block:
    - name: Check role_nutanix_prism_eula_host
      ansible.builtin.fail:
        msg: "the variable 'role_nutanix_prism_eula_host' has to be provided."
      when:
        - role_nutanix_prism_eula_host is not defined or role_nutanix_prism_eula_host == ""

    - name: Check role_nutanix_prism_eula_host_password
      ansible.builtin.fail:
        msg: "the variable 'role_nutanix_prism_eula_host_password' has to be provided."
      when:
        - role_nutanix_prism_eula_host_password is not defined or role_nutanix_prism_eula_host_password == ""

    - name: Check role_nutanix_prism_eula_full_name, role_nutanix_prism_eula_company_name and role_nutanix_prism_eula_job_title
      ansible.builtin.fail:
        msg:
          "the variables 'role_nutanix_prism_eula_full_name', 'role_nutanix_prism_eula_company_name' and \
          'role_nutanix_prism_eula_job_title' must be provided to accept the Nutanix EULA."
      when:
        - role_nutanix_prism_eula_full_name is not defined or role_nutanix_prism_eula_full_name == ""
        - role_nutanix_prism_eula_company_name is not defined or role_nutanix_prism_eula_company_name == ""
        - role_nutanix_prism_eula_job_title is not defined or role_nutanix_prism_eula_job_title == ""
